default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>

development:
  <<: *default

test:
  <<: *default
  database: geolocation_test


production:
  <<: *default
