default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000
  username: postgres
  password: postgres
  database: geolocation

development:
  <<: *default

test:
  <<: *default
  database: geolocation_test

production:
  <<: *default
